name: Docker Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build and Test Phase
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # or 'zulu', 'adopt', etc.
          java-version: '17' 

      # Step 3: Cache Maven dependencies (optional but speeds up builds)
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

 

      # Step 5: Install dependencies and run tests
      - name: Run Tests
        run: mvn clean test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Dockerfile
        uses: docker/build-push-action@v4
        with:
          context: ./front-end
          file: ./front-end/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/foyer-front:v-${{ github.run_number }}

  update-config:
    needs: deploy
    permissions:
       contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: changing the deployment of git repo
        with:
          repository: '${{ secrets.GIT_USERNAME }}/kube-manifest'
          token: ${{ secrets.GIT_TOKEN }}
      - name: modify the image
        run: |
          git config user.email ahmed7hmila@gmail.com
          git config user.name Ahmed
          sed -i "s+${{ secrets.DOCKERHUB_USERNAME }}/foyer-front.*+${{ secrets.DOCKERHUB_USERNAME }}/foyer-front:v-$RUN_NUMBER+g" ./deployment-angular-app.yaml
          git add .
          git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
          git push origin main
        env:
            GIT_PASSWORD: ${{ secrets.GIT_TOKEN }}
            RUN_NUMBER: ${{ github.run_number }}
